# Generated by Django 5.0.2 on 2024-03-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosider', '0003_invoiceitem_total_ht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total_ht',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
